---
title: "Supplemental figures"
output: 
  html_document:
    df_print: paged
author: "John Favate"
date: "`r Sys.time()`"
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r}
# Prevent printing of warnings and such in the HTML
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.align = "center")
```

```{r}
library(tidyverse)
library(ggpubr)
library(scales)
```

Read in the data
```{r}
kdf <- read_csv("../data_frames/kallisto_results.csv")
```

### Correlations between read counts for replicates

```{r}
cors.counts <- kdf %>% 
  select(sample, target_id, est_counts) %>% 
  mutate(repl = str_sub(sample, start = -1),
         sample = str_sub(sample, end = -3),
         est_counts = ifelse(est_counts == 0, NA, log10(est_counts))) %>% 
  split(.$sample) %>% 
  map(function(x){
    # calculate all possible pairwise cors within a sample set
    cor.mat <- x %>% 
      pivot_wider(names_from = c(sample, repl), values_from = est_counts) %>% 
      select(-target_id) %>% 
      cor(use = "pairwise.complete.obs")
    
    # remove the lower half of redundancy
    cor.mat[lower.tri(cor.mat)] <- NA
    
    cor.mat %>% 
      as_tibble(rownames = "s1") %>% 
      pivot_longer(where(is.numeric), names_to = "s2", values_to = "R") %>% 
      filter(s1 != s2)
  }) %>% 
  bind_rows(.id = "set") %>% 
  mutate(s1 = str_sub(s1, start = -1),
         s2 = str_sub(s2, start = -1))

cors.counts
```

Plot it
```{r fig.width = 5, fig.height = 4}
p.counts.cors <- cors.counts %>% 
  ggplot(., aes(s1, s2, label = signif(R, 3)))+
  geom_text()+
  facet_wrap(~set, scales = "free", ncol = 3)+
  theme_bw()+
  theme(text = element_text(size = 13),
        panel.grid.major = element_blank())+
  labs(x = NULL, y = NULL)+
  geom_vline(aes(xintercept = 1.5), size =.3)+
  geom_vline(aes(xintercept = 2.5), size =.3)+
  geom_hline(aes(yintercept = 1.5), size =.3)+
  geom_hline(aes(yintercept = 2.5), size =.3)

p.counts.cors

ggsave(plot = p.counts.cors, filename = "../figures/counts_cors.png", width = 5, height = 4)
```

### TPM correlations

Similar, except with them all in one plot
```{r}
cor.mat <- kdf %>%
  select(sample, target_id, tpm) %>%
  mutate(tpm = ifelse(tpm == 0, NA, log10(tpm))) %>%
  pivot_wider(names_from = sample, values_from = tpm) %>%
  # flipping this ensures better ordering on the heatmap
  select("minusADPRC-2", "minusADPRC-1", everything(), -target_id) %>%
  cor(use = "pairwise.complete.obs")

# remove the lower half of redundancy
cor.mat[upper.tri(cor.mat)] <- NA

cors.tpm <- cor.mat %>%
  as_tibble(rownames = "s1") %>%
  pivot_longer(where(is.numeric), names_to = "s2", values_to = "R") %>%
  filter(s1 != s2 & !is.na(R))

# extract cor for minusADPRC
adprc.cor <- cors.tpm %>% 
  filter(grepl("ADPRC", s1) & grepl("ADPRC", s2)) %>% 
  pull(R)

# remove that row and add it back with the names reverse
cors.tpm <- cors.tpm %>% 
  filter(!(grepl("ADPRC", s1) & grepl("ADPRC", s2))) %>% 
  add_case(s1 = "minusADPRC-2", s2 = "minusADPRC-1", R = adprc.cor)

cors.tpm
```

```{r fig.width=8, fig.height = 5}
p.cors.tpm <- cors.tpm %>% 
  ggplot(., aes(s1, s2, fill = R))+
  geom_tile()+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 30, hjust = 1))+
  theme(text = element_text(size = 13),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "black", linetype = 3, size = .2))+
  labs(x = NULL,
       y = NULL)+
  scale_fill_viridis_c(option = "B")

p.cors.tpm

ggsave(plot = p.cors.tpm, filename = "../figures/tpm_cors.png", width = 8, height = 5)
```

### Read count distributions

These are rounded read counts.
```{r fig.width = 6, fig.height = 3.5}
p.rc.dist <- kdf %>%
  mutate(Replicate = str_sub(sample, start = -1),
         sample = str_sub(sample, end = -3),
         est_counts = round(est_counts)) %>%
  filter(est_counts > 0) %>% 
  ggplot(., aes(sample, est_counts, color = Replicate)) +
  geom_point(
    position = position_jitterdodge(jitter.height = 0, jitter.width = .2),
    size = 1
  ) +
  geom_boxplot(aes(linetype = Replicate), # this is so I can make them black and let the points be colored
               outlier.colour = NA,
               fill = NA,
               color = "black",
               show.legend = FALSE) +
  scale_y_log10(labels = trans_format("log10", math_format(10 ^ .x))) +
  theme_bw() +
  theme(
    text = element_text(size = 13),
    panel.grid = element_blank(),
    axis.text.x = element_text(angle = 20, hjust = 1)
  ) +
  labs(x = NULL,
       y = "Reads per gene")+
  scale_linetype_manual(values = c(1,1,1))

p.rc.dist

ggsave(plot = p.rc.dist, filename = "../figures/rc_dist.png", width = 6, height = 3.5)
```

### genes with zero reads

```{r}
kdf %>% 
  mutate(Replicate = str_sub(sample, start = -1),
         sample = str_sub(sample, end = -3)) %>% 
  filter(est_counts == 0) %>% 
  ggplot(., aes(sample, fill = Replicate))+
  geom_bar(position = "dodge")+
  theme_bw()+
  theme(text = element_text(size = 13),
        panel.grid = element_blank(),
        axis.text.x = element_text(angle = 20, hjust = 1))+
  labs(x = NULL,
       y = "Genes with 0 reads")
```

